default-members = ["crates/vitesse"]

[workspace]
resolver = "2"
members = [
    "crates/vitesse"
]

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed.git", rev = "1564bd82f25c3cef74da581489c31389810d39f7" }
